### ISSUE TITLE
Which file do I need if I want to put this model into production?

### ISSUE THREAD

**Issue by astrike30** [keplerlab/neuralCreativityServer#1]
Hi, I am developing an app that could use your model to identify sketches. I found your model after a huge amount of searching and I think it is exactly what I need, basically, I would continuously provide the model with a sketch and have it output the result. I have a few questions though:

1. If I only need the model is [this](https://github.com/keplerlab/neuralCreativityServer/tree/master/server/caffeModel) the file that I would need?
2. I see that in your [deploy.prototxt](https://github.com/keplerlab/neuralCreativityServer/blob/master/server/caffeModel/deploy.prototxt) in that file this is the input format `input_shape {
  dim: 1
  dim: 1
  dim: 128
  dim: 128
}` could you point me to some documentation for this / how I would convert a png to it? I have seen it around Caffe but can't find documentation. I think it has something to do with batch size, RGB, the size of the image and so on but how would I even input say a png or something to that?

I am an intermediate programmer (I think) and have been doing it for about a year (hence my being able to use your model for an application) but I am a complete beginner to machine learning and still taking courses and stuff, would love to contribute to this in the future then.

Thanks for taking any time to help and dealing with my nooby questions.

**Comment by mayank10j** [comment]
1) Yes this is is the Trained model in caffe Model file format.  If you want to do prediction using pre trained model this is the file you are looking for. 
2) This model expects single channel monochrome 128x128 size image as input.  This project uses OpenCV DNN Importer for forward pass and converts any png jpeg to 128x128 size using OpenCV. 
Hope this helps. See ( https://github.com/keplerlab/neuralCreativityServer/blob/master/server/src/neuralCreativityMain.cpp) line 310 to 334.

**Comment by astrike30** [comment]
Thanks so much for the help, will be in contact if I have any more questions. Keep up the great work.
